### ENDPOINTS

### API DE USERS -> /api/users
### API DE EVENTOS -> /api/events

### obtener todos los datos
GET http://localhost:5000/api/users/all

### obtener un user
GET http://localhost:3000/api/users/0
### crear un nuevo user
POST http://localhost:5000/api/users/new
Content-Type: application/json

{
  "id": "13443",
  "name": "Atila"
}

### modificar un user)
PATCH http://localhost:5000/api/users/upd/:id
Content-Type: application/json
{
  "name": "Atilaseeo",
}

### borrar un user
DELETE http://localhost:5000/api/users/del/:id
### reemplazar un user
PUT http://localhost:5000/api/users/rep/:id